### ISSUE TITLE
Clavin Error opening gazetteer index.

### ISSUE THREAD

**Issue by dbl001** [Berico-Technologies/CLAVIN#108]
I'm getting this error 'Clavin Error opening gazetteer index.'  running CLIFF. 
Any ideas on what I missed?

       // run an initial throw-away query just to "prime the pump" for
        // the cache, so we can accurately measure performance speed
        // per: http://wiki.apache.org/lucene-java/ImproveSearchingSpeed
        indexSearcher.search(new AnalyzingQueryParser(Version.LUCENE_4_9, INDEX_NAME.key(),
                INDEX_ANALYZER).parse("Reston"), null, DEFAULT_MAX_RESULTS, POPULATION_SORT);
        } catch (ParseException pe) {
            throw new ClavinException("Error executing priming query.", pe);
        } catch (IOException ioe) {
            throw new ClavinException("Error opening gazetteer index.", ioe);
        }
    }

Failed tests: 
  GeoNameLookupTest.testCountryLookup:16 expected:<0> but was:<250>
  GeoNameLookupTest.testAdm1Lookup:24 expected:<0> but was:<3895>

Tests in error: 
  EntityParserTest.extractAndResolveFromSentences:30 » Clavin Error opening gaze...
  ParseManagerTest.testState:44 NullPointer
  ParseManagerTest.testCity:31 NullPointer
  ParseManagerTest.testCountry:18 NullPointer
  BlacklistTest.testReddit:16 » Clavin Error opening gazetteer index.
  CustomLuceneLocationResolverTest.testGetByGeoNameId:21 » Clavin Error opening ...
  DemonymPlaceTest.testAustralian:35 » Clavin Error opening gazetteer index.
  DemonymPlaceTest.testDemonymInArticle:22 » Clavin Error opening gazetteer inde...
  DemonymPlaceTest.testAmerican:42 » Clavin Error opening gazetteer index.
  DemonymPlaceTest.testIndonesian:49 » Clavin Error opening gazetteer index.
  DemonymPlaceTest.testChinese:28 » Clavin Error opening gazetteer index.
  DemonymPlaceTest.testEuropean:56 » Clavin Error opening gazetteer index.
  DemonymPlaceTest.testAfghanistan:64 » Clavin Error opening gazetteer index.
  AmazonPlaceTest.testAmazon:17 » Clavin Error opening gazetteer index.
  ArlingtonVirginiaPlaceTest.testAbbreviation:27 » Clavin Error opening gazettee...
  AsiaPlaceTest.testAsia:15 » Clavin Error opening gazetteer index.
  BangorMainePlaceTest.testBangorMaine:17 » Clavin Error opening gazetteer index...
  ColomboPlaceTest.testColombo:15 » Clavin Error opening gazetteer index.
  DelawarePlaceTest.testDelawareState:17 » Clavin Error opening gazetteer index.
  DelawarePlaceTest.test10kReportMention:27 » Clavin Error opening gazetteer ind...
  FranceNLPPlaceTest.testFranceFromNlp:28 » Clavin Error opening gazetteer index...
  HandCodedDisambiguationTest.testHuffPoHandCodedArticles:29->verifyArticlesMentionHandCodedCountry:47 » Clavin
  LondonRusselSqPlaceTest.testRussellSq:16 » Clavin Error opening gazetteer inde...
  MiddleEastPlaceTest.testMiddleEastExample:15 » Clavin Error opening gazetteer ...
  MinnesotaPlaceTest.testMinnesotaExample:15 » Clavin Error opening gazetteer in...
  MultiCountryPlaceTest.testCountryExample:15 » Clavin Error opening gazetteer i...
  OklahomaPlaceTest.testOklahoma:17 » Clavin Error opening gazetteer index.
  SantoDomingoPlaceTest.testSantoDomingo:14 » Clavin Error opening gazetteer ind...
  SaoPauloPlaceTest.testSaoPauloAccents:18 » Clavin Error opening gazetteer inde...
  UnitedKingdomPlaceTest.testUkExample:15 » Clavin Error opening gazetteer index...
  UnitedStatesPlaceTest.testUsExample:15 » Clavin Error opening gazetteer index.
  GeoNameAncestryTest.test:22 » NullPointer

Tests run: 48, Failures: 2, Errors: 32, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:38 min
[INFO] Finished at: 2015-08-24T10:43:38-08:00
[INFO] Final Memory: 9M/180M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project stanford-entity-extractor: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/davidlaxer/CLIFF/stanford-entity-extractor/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc

**Comment by dbl001** [comment]
Same issue?

https://travis-ci.org/Berico-Technologies/CLAVIN/builds/43877173

**Comment by ppiersonbt** [comment]
@dbl001 I have seen build issues like think on the CLAVIN-rest repo when the allCountries.txt was missing/incomplete/not indexed properly.

**Comment by dbl001** [comment]
I was missing the symbolic link to /etc/cliff2/IndeDirectory

sudo ln -s /Users/blahblahblah/CLAVIN/IndexDirectory /etc/cliff2/IndexDirectory
