### ISSUE TITLE
How can i get place name if i pass lat,long

### ISSUE THREAD

**Issue by srijiths** [Berico-Technologies/CLAVIN#114]
Is it possible to do a reverse search , like passing a geo coordinate and getting the place name and its details. 

Thank You

**Comment by jmglesner** [comment]
No, that's not a case we've solved for yet. We always appreciate
contributions, though.

**Comment by charlieg** [comment]
@srijiths What you're describing is the use case of a reverse geocoder, not a geoparser like CLAVIN.

https://en.m.wikipedia.org/wiki/Reverse_geocoding

There are many geocoder tools available that provide reverse geocoding capabilities, and it would not make sense to add that kind of feature to CLAVIN.

**Comment by srijiths** [comment]
Thanks @charlieg @jillesvangurp . Closing this issue.
